### ISSUE TITLE
Error al ejecutar

### ISSUE THREAD

**Issue by isaioliva** [johnspart/taxi-project#1]
Hola 

Tengo este error al ejecutar el proyecto
![image](https://user-images.githubusercontent.com/38478132/122616019-924a3100-d057-11eb-9563-3dd456059f60.png)

![image](https://user-images.githubusercontent.com/38478132/122616528-8874fd80-d058-11eb-9693-e508fe53f546.png)

![image](https://user-images.githubusercontent.com/38478132/122616546-8f9c0b80-d058-11eb-98b2-7001fa886a3a.png)

**Comment by johnspart** [comment]
Hola disculpa. Se me fue algo en la documentación que no era. Ya la corregi, se Elimina`boot-webflux:` para el comando inicial queda `./gradlew bootRun`
